package net.unit8.raoh.examples.spring.membership;

import net.unit8.raoh.encode.Encoder;
import net.unit8.raoh.examples.spring.membership.JsonMembershipDecoders.CreateUserCommand;

import org.jspecify.annotations.Nullable;

import java.util.Map;

import static net.unit8.raoh.encode.MapEncoders.*;
import static net.unit8.raoh.encode.ObjectEncoders.*;

/**
 * Map boundary encoders for the membership domain — the write-side mirror of
 * {@link MapMembershipDecoders}.
 *
 * <p>Where {@link MapMembershipDecoders#USER_ROW} decodes a {@code Map<String, Object>} JDBC row
 * into a {@link User}, the encoders here turn domain values back into the same flat column map.
 * {@code contramap} unwraps each value object on the way out ({@code UserId -> long},
 * {@code EmailAddress -> String}), mirroring how the decoder's {@code map(...)} wraps them.
 */
public final class MapMembershipEncoders {

    private MapMembershipEncoders() {}

    /**
     * Encodes a decoded {@link CreateUserCommand} into the columns an {@code INSERT} writes
     * ({@code name}, {@code email}).
     *
     * <p>The command is what {@link JsonMembershipDecoders#CREATE_USER} produces from the request
     * body, so the write path is a straight decode-then-encode pipeline: JSON in, column map out.
     * The {@code id} is generated by the database and therefore is not part of this shape.
     */
    public static final Encoder<CreateUserCommand, Map<String, @Nullable Object>> NEW_USER_ROW = object(
            property("name",  CreateUserCommand::name,  string()),
            property("email", CreateUserCommand::email, string().contramap(EmailAddress::value)));

    /**
     * Encodes a persisted {@link User} into a full column map ({@code id}, {@code name},
     * {@code email}) — the exact inverse of {@link MapMembershipDecoders#USER_ROW}, suitable for an
     * {@code UPDATE} that addresses the row by its existing id.
     */
    public static final Encoder<User, Map<String, @Nullable Object>> USER_ROW = object(
            property("id",    User::id,    long_().contramap(UserId::value)),
            property("name",  User::name,  string()),
            property("email", User::email, string().contramap(EmailAddress::value)));
}
