package net.unit8.raoh.gsh.maven;

import org.junit.jupiter.api.Test;
import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.CsvSource;
import org.w3c.dom.Document;
import org.w3c.dom.Element;
import org.w3c.dom.Node;
import org.w3c.dom.NodeList;

import javax.xml.parsers.DocumentBuilderFactory;
import java.io.InputStream;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNotNull;

/**
 * Verifies the Maven-facing contract of {@link GuardWeaveMojo} by asserting on the plugin descriptor
 * ({@code META-INF/maven/plugin.xml}) that {@code maven-plugin-plugin} generates from the mojo's
 * annotations during the build.
 *
 * <p>{@code GuardWeaveMojoTest} drives {@link GuardWeaveMojo#execute()} with its {@code @Parameter}
 * fields set by reflection, so it never exercises the annotation-derived wiring: the
 * {@code @Mojo(name, defaultPhase)} binding, the {@code @Parameter(property = ...)} names, and the
 * {@code @Parameter(defaultValue = ...)} expressions. A rename or typo in any of those would leave
 * that test green but break real {@code mvn} usage. This test closes that gap by reading the same
 * descriptor Maven consumes.
 *
 * <p>The descriptor is generated by the {@code descriptor} goal (bound to {@code process-classes}),
 * so it is present under {@code target/classes} — on the test classpath — by the time Surefire runs.
 */
class GuardWeaveMojoDescriptorTest {

    private static final String DESCRIPTOR = "/META-INF/maven/plugin.xml";

    /** Parses the generated plugin descriptor from the test classpath. */
    private static Document descriptor() throws Exception {
        var factory = DocumentBuilderFactory.newInstance();
        // Our own build artifact, but disable external entity resolution on principle.
        factory.setFeature("http://apache.org/xml/features/nonvalidating/load-external-dtd", false);
        try (InputStream in = GuardWeaveMojoDescriptorTest.class.getResourceAsStream(DESCRIPTOR)) {
            assertNotNull(in, "plugin.xml must be generated under target/classes before tests run");
            return factory.newDocumentBuilder().parse(in);
        }
    }

    /** The single {@code <mojo>} element for the {@code weave} goal. */
    private static Element weaveMojo() throws Exception {
        NodeList mojos = descriptor().getElementsByTagName("mojo");
        assertEquals(1, mojos.getLength(), "descriptor should declare exactly one mojo");
        return (Element) mojos.item(0);
    }

    /** Text content of the first direct child of {@code parent} named {@code tag}, or null if absent. */
    private static String childText(Element parent, String tag) {
        NodeList children = parent.getChildNodes();
        for (int i = 0; i < children.getLength(); i++) {
            Node n = children.item(i);
            if (n.getNodeType() == Node.ELEMENT_NODE && n.getNodeName().equals(tag)) {
                return n.getTextContent().trim();
            }
        }
        return null;
    }

    /** The {@code <configuration>} entry element for a parameter (e.g. {@code <testTarget>}). */
    private static Element configEntry(String name) throws Exception {
        NodeList configs = weaveMojo().getElementsByTagName("configuration");
        assertEquals(1, configs.getLength(), "mojo should have one <configuration> block");
        NodeList entries = configs.item(0).getChildNodes();
        for (int i = 0; i < entries.getLength(); i++) {
            Node n = entries.item(i);
            if (n.getNodeType() == Node.ELEMENT_NODE && n.getNodeName().equals(name)) {
                return (Element) n;
            }
        }
        return null;
    }

    @Test
    void bindsWeaveGoalToProcessTestClasses() throws Exception {
        Element mojo = weaveMojo();
        assertEquals("weave", childText(mojo, "goal"),
                "the @Mojo(name) must stay 'weave' — pom executions reference this goal");
        assertEquals("process-test-classes", childText(mojo, "phase"),
                "the @Mojo(defaultPhase) must resolve to process-test-classes so test-classes exist when weaving");
        assertEquals("net.unit8.raoh.gsh.maven.GuardWeaveMojo", childText(mojo, "implementation"),
                "the descriptor must point at the mojo implementation class");
    }

    @ParameterizedTest(name = "{0} → {1}")
    @CsvSource({
            "packages,   ${raoh.gsh.packages}",
            "classes,    ${raoh.gsh.classes}",
            "exclude,    ${raoh.gsh.exclude}",
            "config,     ${raoh.gsh.config}",
            "target,     ${raoh.gsh.target}",
            "testTarget, ${raoh.gsh.testTarget}",
            "weaveMain,  ${raoh.gsh.weaveMain}",
    })
    void exposesUserPropertyForEachParameter(String param, String expectedProperty) throws Exception {
        Element entry = configEntry(param);
        assertNotNull(entry, "configuration must declare an entry for " + param);
        assertEquals(expectedProperty, entry.getTextContent().trim(),
                "the @Parameter(property) for " + param + " is the CLI/-D contract and must not change silently");
    }

    @Test
    void defaultsTargetDirectoriesToProjectBuildOutputs() throws Exception {
        assertEquals("${project.build.outputDirectory}", configEntry("target").getAttribute("default-value"),
                "target must default to the main output directory");
        assertEquals("${project.build.testOutputDirectory}", configEntry("testTarget").getAttribute("default-value"),
                "testTarget must default to the test output directory");
    }

    @Test
    void defaultsWeaveMainToFalse() throws Exception {
        assertEquals("false", configEntry("weaveMain").getAttribute("default-value"),
                "weaveMain must default to false so guards never leak into packaged main artifacts");
    }
}
